version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamfactory
      MYSQL_USER: df_admin
      MYSQL_PASSWORD: df_admin
  redis:
    image: redis
  df:
    image: dreamfactorysoftware/df-docker
    environment:
      DB_HOST: mysql
      DB_USERNAME: df_admin
      DB_PASSWORD: df_admin
      DB_DATABASE: dreamfactory
      REDIS_HOST: redis
      REDIS_DATABASE: 0
      REDIS_PORT: 6379
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
